#ifndef OOMPH_CLEAN_OUTPUT_HEADER
#define OOMPH_CLEAN_OUTPUT_HEADER

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
  #include <oomph-lib-config.h>
#endif

// oomph-lib headers
#include "../axisym_navier_stokes/Taxisym_navier_stokes_elements.h"


namespace oomph
{



class CleanOutputAxisymmetricTTaylorHoodElement : public virtual AxisymmetricTTaylorHoodElement
{

  public:

 /// Empty constructor
 CleanOutputAxisymmetricTTaylorHoodElement(){};

 /// Empty virtual constructor
 ~CleanOutputAxisymmetricTTaylorHoodElement(){};

 
 /// Overload the output function
    void output(std::ostream& outfile, const unsigned& n_plot);

    /// Overload the output function in .cc file
    void output(std::ostream& outfile)
    {
       unsigned nplot = 5;
      output(outfile, nplot);
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      FiniteElement::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      FiniteElement::output(file_pt, n_plot);
    }

  

};
  

} //namespace oomph

#endif
